WITH july_sum AS (
  SELECT FLAVOR, SUM(TOTAL_ORDER) AS july_total
  FROM JULY
  GROUP BY FLAVOR
)
SELECT A.FLAVOR
FROM FIRST_HALF AS A
JOIN july_sum AS B ON A.FLAVOR = B.FLAVOR
ORDER BY (A.TOTAL_ORDER + B.july_total) DESC
LIMIT 3;
